AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 App Stack

Parameters:
  VpcId:
    Type: String
    Description: The VPC id
  PublicSubnetId:
    Type: String
    Description: The public subnet id

Resources:
  EC2Role:
    Type: AWS::IAM::Role 
    Properties:
      RoleName: !Sub "${AWS::StackName}-EC2Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
      # SSM agent
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      # CloudWatch agent
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role
    
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourcePrefixListId: pl-0bd77a95ba8e317a6
  
  # Elastic IP
  WebServerEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # Associate the EIP with the EC2 instance
  WebServerEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Instance
      EIP: !Ref WebServerEIP
  
  Instance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          commands:
            nginx:
            00_create_nginx_user:
              command: useradd -r -s /sbin/nologin nginx || true
            01_install_nginx:
              command: amazon-linux-extras install nginx1 -y
            02_enable_nginx:
              command: yum install -y php php-fpm amazon-ssm-agent amazon-cloudwatch-agent 
            enable_nginx:
              command: amazon-linux-extras enable nginx -y 
            chown_www:
              command: chown -R nginx:nginx /usr/share/nginx/html
          files:
            /var/www/html/index.php:
              content: |
                <?php
                echo "Hello world! from EC2 with SSM and CW Agent";
              mode: '0644'
              owner: root
              group: root
            /etc/nginx/conf.d/default.conf:
              content: |
                server {
                    listen 80 default_server;
                    server_name _;
                    root /var/www/html;
                    index index.php index.html;
                    
                    location / {
                        try_files $uri $uri/ =404;
                    }

                    location ~ \.php$ {
                        include fastcgi_params;
                        fastcgi_pass 127.0.0.1:9000;
                        fastcgi_index index.php;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    }
                }
              mode: '0644'
              owner: root
              group: root
              content: |
                {
                  "agent": {
                    "metrics_collection_interval": 60,
                    "run_as_user": "root"
                  },
                  "metrics": {
                    "namespace": "EC2/App",
                    "metrics_collected": {
                      "cpu": {
                        "measurement": ["cpu_usage_idle","cpu_usage_system","cpu_usage_user"],
                        "metrics_collection_interval": 60,
                        "resources": ["*"]
                      },
                      "mem": {
                        "measurement": ["mem_used_percent"],
                        "metrics_collection_interval": 60
                      }
                    }
                  }
                }
              mode: '0644'
              owner: root
              group: root
          services:
            sysvinit:
              nginx:
                enabled: true
                ensureRunning: true
              php-fpm:
                enabled: true
                ensureRunning: true
              amazon-ssm-agent:
                enabled: true
                ensureRunning: true
              amazon-cloudwatch-agent:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: t3.small
      ImageId: !Sub 'resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -xe
        yum install -y aws-cfn-bootstrap
        /opt/aws/bin/cfn-init -v --stack !Ref 'AWS::StackName' --resource Instance --region !Ref 'AWS::Region'
        /opt/aws/bin/cfn-signal -e $? --stack !Ref 'AWS::StackName' --resource Instance --region !Ref 'AWS::Region'

Outputs:
  EC2Id:
    Description: "Instance ID"
    Value: !Ref Instance
  
