AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 App Stack

Parameters:
  VpcId:
    Type: String
    Description: The VPC id
  PublicSubnetId:
    Type: String
    Description: The public subnet id

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  # Elastic IP
  WebServerEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # Associate the EIP with the EC2 instance
  WebServerEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Instance
      EIP: !Ref WebServerEIP
  
  Instance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              nginx: []
              php: []
              php-fpm: []
          files:
            /var/www/html/index.php:
              content: |
                <?php
                echo "Hello world!";
              mode: '0644'
              owner: nginx
              group: nginx
            /etc/nginx/conf.d/default.conf:
              content: |
                server {
                    listen 80 default_server;
                    server_name _;
                    root /var/www/html;
                    index index.php index.html;
                    
                    location / {
                        try_files $uri $uri/ =404;
                    }

                    location ~ \.php$ {
                        include fastcgi_params;
                        fastcgi_pass 127.0.0.1:9000;
                        fastcgi_index index.php;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    }
                }
              mode: '0644'
              owner: root
              group: root
          services:
            sysvinit:
              nginx:
                enabled: true
                ensureRunning: true
              php-fpm:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: t3.small
      ImageId: !Sub 'resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -xe
        yum install -y aws-cfn-bootstrap
        /opt/aws/bin/cfn-init -v --stack !Ref 'AWS::StackName' --resource Instance --region !Ref 'AWS::Region'
        /opt/aws/bin/cfn-signal -e $? --stack !Ref 'AWS::StackName' --resource Instance --region !Ref 'AWS::Region'

Outputs:
  EC2Id:
    Description: "EC2 instance ID"
    Value: !Ref Instance
