version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing/upgrading AWS CLI"
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo "Validating root stack..."
      - aws cloudformation validate-template --template-body file://root-stack.yaml
  build:
    commands:
      - echo "Deploying root stack (VPC nested stack)..."
      
artifacts:
  files:
    - root-stack.yaml
    - vpc-stack.yaml
