AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack to deploy VPC as nested stack

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc-stack.yaml   

  Appstack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./app-stack.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3-stack.yaml

Outputs:
  VpcId:
    Description: "VPC ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.VpcId
  PublicSubnetId:
    Description: "Public Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PublicSubnetId
  EC2Id:
    Description: "EC2 instance ID from app stack"
    Value: !GetAtt Appstack.Outputs.EC2Id
