AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack to deploy VPC as nested stack

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc-stack.yaml   

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs-stack.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId1: !GetAtt VPCStack.Outputs.PublicSubnetId1
        PublicSubnetId2:  !GetAtt VPCStack.Outputs.PublicSubnetId2
        PrivateSubnetId1: !GetAtt VPCStack.Outputs.PrivateSubnetId1
        PrivateSubnetId2: !GetAtt VPCStack.Outputs.PrivateSubnetId2

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3-stack.yaml

Outputs:
  VpcId:
    Description: "VPC ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.VpcId
  PublicSubnetId1:
    Description: "Public Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PublicSubnetId1
  PublicSubnet2:
    Description: "Public Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PublicSubnetId2
  PrivateSubnetId1:
    Description: "Private Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnetId1
  PrivateSubnetId2:
    Description: "Private Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnetId2
  ECSId:
    Description: "ECS cluster ID from ECS stack"
    Value: !GetAtt ECSStack.Outputs.ECSId

