AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack to deploy VPC as nested stack

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc-stack.yaml   

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs-stack.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1Id  
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2Id  
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  R53Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./r53-stack.yaml
    Parameters:
      LoadBalancerDNSName: !GetAtt ECSStack.Outputs.LoadBalancerDNS

Outputs:
  VpcId:
    Description: "VPC ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.VpcId
  PublicSubnet1:
    Description: "Public Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1Id  
  PublicSubnet2:
    Description: "Public Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2Id  
  PrivateSubnet1:
    Description: "Private Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1Id 
  PrivateSubnet2:
    Description: "Private Subnet ID from VPC stack"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2Id 
  HostedZoneId:
    Description: "Hosted Zone ID from R53 stack"
    Value: !GetAtt R53Stack.Outputs.HostedZoneId

